#!/bin/sh
if ! whoami &> /dev/null; then
  if [ -w /etc/passwd ]; then
    # Remove existing entry (added by useraddd)
    sed -i '/obpuser/d' /etc/passwd
    # Insert replacement with current uid
    echo "obpuser:x:$(id -u):0:obpuser user:/opt/obp-boostrap-user:/sbin/nologin" >> /etc/passwd
  fi
fi
exec "$@"

